context:
  name: visionworkbench
  version: "3.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/visionworkbench/visionworkbench/archive/refs/tags/${{ version }}.zip
  sha256: ee9ff088930f2fceacdfb0ac740b1228069f5eb8a2d6dee23c7f62a0f235d8a5

build:
  number: 1
  skip: win
  script: build.sh

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake >=3.15
    - make
  host:
    - flann
    - libboost-devel
    - libgdal
    - libblas * *openblas
    - openblas
    - libopencv
    - libjpeg-turbo
    - libpng
    - libtiff

tests:
  - script:
      - hillshade $PREFIX/share/vw/tests/tinyDemAN.tif

about:
  homepage: https://github.com/visionworkbench/visionworkbench
  summary: 'An image processing and computer vision library published by NASA'
  description: |
    The NASA Vision Workbench is a general purpose image processing and computer vision library. It is part of the Ames Stereo Pipeline. 
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  documentation: https://github.com/visionworkbench/visionworkbench
  repository: https://github.com/visionworkbench/visionworkbench

extra:
  recipe-maintainers:
    - oleg-alexandrov
    - hobu
